# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrendingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingApp
pod "youtube-ios-player-helper"
	

end
